### ISSUE TITLE
PHP Fatal error:

### ISSUE THREAD

**Issue by SaiGonSeamus** [offensive-security/masscan-web-ui#17]
Hi,
I'm importing a 2.5GB xml file and getting this error.

```
PHP Fatal error:  String allocation overflow, max size is 2147483647 in /var/www/html/import.php on line 79

Fatal error: String allocation overflow, max size is 2147483647 in /var/www/html/import.php on line 79
```

Any ideas?

Server has plenty of memory 12GB and I have added

`ini_set("memory_limit", -1);`

But get the same error.

**Comment by pawco** [comment]
Which PHP version you are using?
Check this [link](http://php.net/manual/en/language.types.string.php).

**Comment by SaiGonSeamus** [comment]
I'm using 5.5 

I was following the old instructions from the site not github.

**Comment by pawco** [comment]
If you want to process files bigger than 2GB you must use PHP >=7.

> As of PHP 7.0.0, there are no particular restrictions regarding the length of a string on 64-bit builds. On 32-bit builds and in earlier versions, a string can be as large as up to 2GB (2147483647 bytes maximum)
