### ISSUE TITLE
ips displayed as 0.0.0.0 in UI

### ISSUE THREAD

**Issue by vladmolch** [offensive-security/masscan-web-ui#6]
running:
root@tester:/var/www/html# masscan 192.168.1.0/24 --ports 0-1033 --banners --source-ip 192.168.1.222 --max-rate 100000 -oX scan.xml
root@tester:/var/www/html# php import.php scan.xml

Do you want to clear the database before importing (yes/no)?: yes

Clearing the db
Reading file
Parsing file
Processing data (This may take some time depending on file size)

Summary:
Total records:48
Inserted records:48
Took about:4 seconds

When I go to the UI all the ips are 0.0.0.0 
The rest is fine. Worked on it for a while but couldn't figure it out

**Comment by pawco** [comment]
Can you just confirm that IP addresses in scan.xml are ok?

**Comment by vladmolch** [comment]
yep
when run masscan without output i can see the ips:
root@tester:/var/www/html# masscan 192.168.1.0/24 --ports 0-65535 --banners
--source-ip 192.168.1.222 --max-rate 100000

Starting masscan 1.0.3 (http://bit.ly/14GZzcT) at 2016-01-13 15:03:33 GMT
 -- forced options: -sS -Pn -n --randomize-hosts -v --send-eth
Initiating SYN Stealth Scan
Scanning 256 hosts [65536 ports/host]
Discovered open port 1026/tcp on
192.168.1.19
Discovered open port 445/tcp on
192.168.1.19
Discovered open port 631/tcp on
192.168.1.12
Discovered open port 135/tcp on
192.168.1.19
Discovered open port 63100/tcp on
192.168.1.100
Discovered open port 63100/tcp on
192.168.1.101
Discovered open port 10243/tcp on
192.168.1.19
Discovered open port 56789/tcp on
192.168.1.19
Discovered open port 902/tcp on
192.168.1.19
Discovered open port 63147/tcp on
192.168.1.101
Discovered open port 3389/tcp on
192.168.1.201
Banner on port 63100/tcp on 192.168.1.101: [unknown]
MER:01/13/2016-15:04:18 Not deleting the task
Fn[__IHN_tcpServerDeleteConnectionThread] at
Ln[442]\x0a\x0aMER:01/13/2016-15:04:20 MA_DrawPromoScreensaver :: Drawing
PROMO SS here \x0a\x0a
Discovered open port 139/tcp on
192.168.1.19
Discovered open port 8443/tcp on 192.168.1.1

On Wed, Jan 13, 2016 at 10:37 AM, pawco <notifications@github.com> wrote:

> Can you just confirm that IP addresses in scan.xml are ok?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/offensive-security/masscan-web-ui/issues/6#issuecomment-171333376>
> .
>



-- 
*Vlad*

**Comment by pawco** [comment]
OK. Thanks.
I'll create some test xml with private IPs and check. I'll post my findings here...

**Comment by vladmolch** [comment]
ok thx

On Wed, Jan 13, 2016 at 10:41 AM, pawco <notifications@github.com> wrote:

> OK. Thanks.
> I'll create some test xml with private IPs and check. I'll post my
> findings here...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/offensive-security/masscan-web-ui/issues/6#issuecomment-171334585>
> .
>



-- 
*Vlad*

**Comment by vladmolch** [comment]
here is what i am seeing...
(attached)

On Wed, Jan 13, 2016 at 10:41 AM, pawco <notifications@github.com> wrote:

> OK. Thanks.
> I'll create some test xml with private IPs and check. I'll post my
> findings here...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/offensive-security/masscan-web-ui/issues/6#issuecomment-171334585>
> .
>



-- 
*Vlad*

**Comment by pawco** [comment]
I don't see attachment?! Can you try again? Screenshot will help...

**Comment by vladmolch** [comment]
resenting...
[image: Inline image 1]

On Wed, Jan 13, 2016 at 11:03 AM, pawco <notifications@github.com> wrote:

> I don't see attachment?! Can you try again? Screenshot will help...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/offensive-security/masscan-web-ui/issues/6#issuecomment-171343093>
> .
>



-- 
*Vlad*

**Comment by pawco** [comment]
Hm, I still don't see the image...just text [image: Inline image 1]...
Never mind....

I run a scan the same way...and all looks good to me....
![masscan-ui-scan-example](https://cloud.githubusercontent.com/assets/9696673/12322147/a4ebb416-bab2-11e5-8401-072c064bf2f7.jpeg)

Not sure what might be a problem. Can you post your scan.xml here so I can check?

**Comment by vladmolch** [comment]
[scan.zip](https://github.com/offensive-security/masscan-web-ui/files/90429/scan.zip)

**Comment by vladmolch** [comment]
here you go..

**Comment by pawco** [comment]
hm...all looks good...
![masscan-ui-example-2](https://cloud.githubusercontent.com/assets/9696673/12325416/62be564e-baca-11e5-8802-c4ad8645b8c6.jpeg)

**Comment by vladmolch** [comment]
weird...

On Thu, Jan 14, 2016 at 8:24 AM, pawco <notifications@github.com> wrote:

> hm...all looks good...
> [image: masscan-ui-example-2]
> <https://cloud.githubusercontent.com/assets/9696673/12325416/62be564e-baca-11e5-8802-c4ad8645b8c6.jpeg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/offensive-security/masscan-web-ui/issues/6#issuecomment-171643463>
> .
>



-- 
*Vlad*

**Comment by vladmolch** [comment]
i rebuilt the db and reinstalled everything, same thing ...
Doesn't make sense

On Thu, Jan 14, 2016 at 8:24 AM, pawco <notifications@github.com> wrote:

> hm...all looks good...
> [image: masscan-ui-example-2]
> <https://cloud.githubusercontent.com/assets/9696673/12325416/62be564e-baca-11e5-8802-c4ad8645b8c6.jpeg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/offensive-security/masscan-web-ui/issues/6#issuecomment-171643463>
> .
>



-- 
*Vlad*

**Comment by vladmolch** [comment]
btw this is on Kali 2
Linux tester 4.0.0-kali1-686-pae #1 SMP Debian 4.0.4-1+kali2 (2015-06-03)
i686 GNU/Linux

On Thu, Jan 14, 2016 at 8:24 AM, pawco <notifications@github.com> wrote:

> hm...all looks good...
> [image: masscan-ui-example-2]
> <https://cloud.githubusercontent.com/assets/9696673/12325416/62be564e-baca-11e5-8802-c4ad8645b8c6.jpeg>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/offensive-security/masscan-web-ui/issues/6#issuecomment-171643463>
> .
>



-- 
*Vlad*

**Comment by pawco** [comment]
I tested on Ubuntu...but I'll test on Kali too during the day and post results here....

**Comment by vladmolch** [comment]
cool
thx

On Thu, Jan 14, 2016 at 9:39 AM, pawco <notifications@github.com> wrote:

> I tested on Ubuntu...but I'll test on Kali too during the day and post
> results here....
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/offensive-security/masscan-web-ui/issues/6#issuecomment-171660069>
> .
>



-- 
*Vlad*

**Comment by pawco** [comment]
Yes, I can confirm the problem with Kali.
I'm working on fix...

**Comment by vladmolch** [comment]
cool

On Thu, Jan 14, 2016 at 10:18 AM, pawco <notifications@github.com> wrote:

> Yes, I can confirm the problem with Kali.
> I'm working on fix...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/offensive-security/masscan-web-ui/issues/6#issuecomment-171670005>
> .
>



-- 
*Vlad*

**Comment by pawco** [comment]
Fixed. 
Just clone the app again and try. I hope everything will be ok than.

**Comment by vladmolch** [comment]
awesome!!!
it works

On Thu, Jan 14, 2016 at 10:34 AM, pawco <notifications@github.com> wrote:

> Fixed.
> Just clone the app again and try. I hope everything will be ok than.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/offensive-security/masscan-web-ui/issues/6#issuecomment-171675272>
> .
>



-- 
*Vlad*

**Comment by pawco** [comment]
Nice. This issue can be closed now...

**Comment by vladmolch** [comment]
would be nice if when you clicked on "service", if its http[s] it would add
the port to the ip. Now, when it"s an irregular http[s] port it just
defaults to 80
Just a suggestion

On Thu, Jan 14, 2016 at 10:40 AM, pawco <notifications@github.com> wrote:

> Nice. This issue can be closed now...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/offensive-security/masscan-web-ui/issues/6#issuecomment-171676725>
> .
>



-- 
*Vlad*

**Comment by pawco** [comment]
yes, good point. I'll add that in next revision
